### ISSUE TITLE
[Suggestion] Make Crossbow Wielding Pillagers Smarter and Deadlier

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Insane96/EnhancedAI#10]
Would love to see some new options for Pillagers to be smarter and more deadly. Currently they group up (if there are multiple) and basically stand still while slowly reloading and shooting (Sometimes even shooting each other with little regard!) Their strength is really only in numbers, as their attacks are very predictable and slow, and when you get within melee range you can usually kill them before they even get the chance to shoot again.

I suggest adding the same config options skeletons have, for Pillagers with Crossbows. Adding accuracy and more range, as well as the escape/dodge mechanics of skeletons will make Pillagers a much smarter and deadly mob. 

Another idea I have is adding a mechanic similar to Piglins, where they run away and regroup if outnumbered/outclassed (Low HP) in battle. That could be something really cool to see for raids, or when trying to capture one of their outposts.

**Comment by Insane96** [comment]
> Another idea I have is adding a mechanic similar to Piglins, where they run away and regroup if outnumbered/outclassed (Low HP) in battle. That could be something really cool to see for raids, or when trying to capture one of their outposts.

This is not easy to do for Pillagers as Piglins use a much newer "Brain" mechanic.

As for the other changes, those will be released in 2.1!
