### ISSUE TITLE
(Suggestion) Server-Side Only Option

### ISSUE THREAD

**Issue by Fundryi** [Insane96/EnhancedAI#100]
Hi,

Just an idea, but would it be possible to have this mod also  work only on Server without needing it on the Client?
With ofc slimmed downed features.
Just curios.

**Comment by Insane96** [comment]
Yes, but will not happen

**Comment by Insane96** [comment]
Also, tecnically, if you disable the features that require client side stuff, the mod should already work server side only (e.g. spiders throwing webs)

**Comment by Fundryi** [comment]
The problem is, Forge ist check if your running InsaneLib and your mod in both the Client and Server if its on the server.

**Comment by Insane96** [comment]
Yep, I thought it was possible, but only with a Vanilla Client
