### ISSUE TITLE
Enhanced AI causes an Autumnity Turkey insurrection

### ISSUE THREAD

**Issue by Darkmega18** [Insane96/EnhancedAI#101]
**Describe the bug**  
When Autumnity version 4 for MC 1.19.2 is installed, even when the entire animal section is turned off turkey are immediately hostile on getting close and with proceed to try to give you murder.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.2.21
 - Enhanced AI: EnhancedAI-1.8.1-mc1.19.2.jar
 - InsaneLib: InsaneLib-1.7.5-mc1.19.2.jar

**Steps to reproduce**  
1.   Just have the mods together and find some turkey. 
2. Reported by another on the abnormal discord who confirmed it was coming from this mod.

**Screenshots**  
not really screenshottable.

**Logs**  
There is no crash.

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes.

Tested with bare minimum of Enhanced AI + Autumnity (and jei + controlling and mouse tweaks). Another player in the discord for autumnity mentioned it will also cause issue with "neutral" mobs from other mods also. So fixing it for this, may fix it for other mob adding mods.

**Comment by Insane96** [comment]
This sadly is not fixable unless I add specific support for turkeys.
I've discovered a bug anyway, so I'll fix that, but sadly Turkeys have two targeting goals, and one is specific to turkeys.

To fix this, add the turkey to `Base.Targeting.Entity Blacklist` in config.

**Comment by Darkmega18** [comment]
Wait @Insane96 . So I need to use the blacklist REGARDLESS if I literally have base turned off cause I've disabled the feature in general?! what?!

I did say: 
> even when the entire animal section is turned off

**Comment by Insane96** [comment]
I said base, not animal

**Comment by Darkmega18** [comment]
oop. that tops my frick. since I was working on the assumption they are actually animals. >_<'

**Comment by Insane96** [comment]
They are, but the targeting is done for every mob which has a target goal
