### ISSUE TITLE
Zombie miner block blacklist in config

### ISSUE THREAD

**Issue by TrustedDriver8900** [Insane96/EnhancedAI#104]
**Describe the bug**  
The problem is the Aternos server crash even if I format the blocks into this
 [minecraft:nether_brick, minecraft:glass, minecraft:nether_brick_slab]

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.1.44
 - Enhanced AI: 1.14.0
 - InsaneLib: 1.10.2

**Steps to reproduce**  
1.   
2.   
3.   

**Screenshots**  
If applicable, add screenshots to help explain

This is the current mods I have.

![Files _ Aternos _ Free Minecraft Server and 12 more pages - Personal - Microsoft​ Edge 20_08_2023 21_19_38](https://github.com/Insane96/EnhancedAI/assets/123337397/0c91e31a-f3cf-4f77-b47f-2b4b7fbdab4a)

**Logs**  
Use a paste site (**pastebin, gist**) to send the game logs (both logs and crash if applicable)  
For the love of god, don't paste the logs here
pastebin: https://pastebin.com/UGmJ8dqK
pastebin pass: Enhanced AI

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
No

**Comment by Insane96** [comment]
You must use quotes for lists
`["minecraft:nether_brick", "minecraft:glass", "minecraft:nether_brick_slab"]`
