### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Willem07** [Insane96/EnhancedAI#109]
Can you make a blacklist for creepers? Some creepers from the Creeper Overhaul mod should attack players, not explode

**Comment by Insane96** [comment]
Is this a feature request or a bug report?

**Comment by Willem07** [comment]
It seemed to me that it was a mistake that the creeper functions are applied to other mobs from mods

**Comment by Insane96** [comment]
Will be fixed in the next update

**Comment by Insane96** [comment]
Fixed in 1.15.3
