### ISSUE TITLE
Village AI

### ISSUE THREAD

**Issue by DonorKrovi** [Insane96/EnhancedAI#110]
**Describe the bug**  
You've added the ability for villagers to attack the player, but they can't walk on the Carpet, in addition to that, they attack the player even in gamemode spectator

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 1.20.1
 - Enhanced AI: EnhancedAI-1.15.4-mc1.20.1
 - InsaneLib: InsaneLib-1.11.1-mc1.20.1

**Steps to reproduce**  
^
**Screenshots**  

**Logs**  
Use a paste site (**pastebin, gist**) to send the game logs (both logs and crash if applicable)  
For the love of god, don't paste the logs here

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes/No

**Comment by Insane96** [comment]
Wdym by "can't walk on carpet"?
Also if I switch to spectator the villager stops following me. That's why I ask to reproduce with EnhancedAI only.

**Comment by Insane96** [comment]
Stale since 1.5 months. Closing
