### ISSUE TITLE
Add melee AI to pillagers

### ISSUE THREAD

**Issue by betterworld-sjq** [Insane96/EnhancedAI#113]
Dumby pillagers should also be able to attack without crossbows. 
Maybe you could also add some more intelligent AI to it, like loading their arrows first when find players, and then rush near to shoot.
But that depends on you, my giant mod maker!

**Comment by Insane96** [comment]
No, sorry. Again, each mob should fulfill a purpose. If every mob can do everything whats the point in having different mobs?
