### ISSUE TITLE
witch crash 1.20.1

### ISSUE THREAD

**Issue by kaairu** [Insane96/EnhancedAI#115]
**Describe the bug**  
crash log says the witch crashed the game it seems

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge:  47.2.1
 - Enhanced AI:  1.15.4
 - InsaneLib: 1.12.0

**Steps to reproduce**  
 N/A

**Screenshots**  
N/A

**Logs**  
https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1165889506872918076/crash-2023-10-22_22.45.47-server.txt?ex=65487e37&is=65360937&hm=1b2bbb551f1a873a556fa3dcf8a817b3016782e52ee624311823478f17606c90&&raw=false

https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1165889507174916146/latest.log?ex=65487e37&is=65360937&hm=5b4816d09c5739c6bfe95b21242f001660bcafa951ec591bf2b6ad2cd4fc70ad&&raw=false

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

**Comment by Insane96** [comment]
Tou replied yes to the last question bu the logs show many mods, did you test with a minimal set of mods or not?

**Comment by kaairu** [comment]
mistyped yes, mb

**Comment by Insane96** [comment]
You need to test with a minimal set of mods then, this already got reported and can't reproduce in vanilla Enhanced AI

**Comment by kaairu** [comment]
seems like i actually reported the same thing 5 months ago and its apparently big brain
