### ISSUE TITLE
Digger Zombies bypasss FTB Chunk claims

### ISSUE THREAD

**Issue by Saereth** [Insane96/EnhancedAI#117]
**Describe the bug**  
Digger zombies are able to mine into your base even with the area claimed which should protect blocks. 

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.2.21
 - Enhanced AI: EnhancedAI-1.8.3-mc1.19.2.jar
 - InsaneLib: InsaneLib-1.7.5-mc1.19.2.jar

**Steps to reproduce**  
1.   Load up an instance with ftbchunks, enhancedai
2.   claim an area
3.   wait and watch as zombies bypass your claims

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  

Yes

**Addiitonal**

This implementation bypasses the forge break events where protections etc would normally be checked
https://github.com/Insane96/EnhancedAI/blob/67afd9bd9dc2711bc858ceec89a9d65712b507fa/src/main/java/insane96mcp/enhancedai/modules/mobs/miner/BlockBreakerGoal.java#L134C1-L147

**Comment by Insane96** [comment]
The protection is for players, so why would it work on zombies?

**Comment by Saereth** [comment]
Because people claim chunks to prevent griefing and having the builds destroyed, it prevents explosions or other players maliciously griefing you by for instance sending an army of computer craft turtles into your base or capturing half a dozen digger zombies and dropping them into your base.

**Comment by Insane96** [comment]
The break event is for players only

**Comment by Saereth** [comment]
Yeah it is for player but also fake player which is what most mods do in this situation to check for protections, implement a temporary fakeplayer, check if the block event is canceled and then proceed or cancel the action.

something like
```
// create fakePlayer from entity
        BlockEvent.BreakEvent event = new BlockEvent.BreakEvent(world, pos, state, fakePlayer);
        MinecraftForge.EVENT_BUS.post(event);
        if (event.isCanceled()) {
            return skip("Break was canceled!");
        }
```

**Comment by Insane96** [comment]
In 2.0.x Zombie miners will now call the `LivingDestroyBlockEvent`
Also in 1.16.10 for 1.18.2, 1.8.4 for 1.19.2, 1.12.5 for 1.19.4
