### ISSUE TITLE
Spiders Can hit players through blocks (nyf's spiders)

### ISSUE THREAD

**Issue by Voltem0** [Insane96/EnhancedAI#118]
**Describe the bug**  
I use Nyf's spiders that makes spiders capable of walking on walls and ceilings. makes them much harder to deal with.
Unfortunately there is some interaction that if you have a bunch of spiders below the player trying to get to them, and if there is only one block separating them, the spiders can attack the player through the floor.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Enhanced AI: 1.15.4
 - InsaneLib: 1.12.0

**Steps to reproduce**  
1.   Have a bunch of nyf's spiders in a box (preferrably cave spiders)
2.   stand ontop of the box
3.   be in survival
4. 4. Enjoy the spider bites.

**Screenshots**  
-

**Logs**  
-
**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes, nyfs spiders and enhanced AI alone will suffice

**Comment by Insane96** [comment]
This is a vanilla bug. Mobs can hit you through walls. https://bugs.mojang.com/browse/MC-2310
Has been fixed in 1.20.2 and will be fixed in EnhancedAI 2.0

**Comment by Voltem0** [comment]
I mean you say that, but without your AI alterations the spiders don't hit me through the floor.
I suppose it could be that vanilla spiders are just too stupid to realize that they can do that, or they just dont see the players through walls the same way as they do with this mod but ultimately it still means with your mod i get hit through walls/floors.

**Comment by Insane96** [comment]
Oh, ok, I will check it then

**Comment by Insane96** [comment]
Wait, does it happen with EnhancedAI only? If it does, it's the vanilla bug, and, as said, will be fixed in 2.0
Also without EAI they don't aggro you through walls so that's why this rarely happens in vanilla.

**Comment by Insane96** [comment]
Stale for 1 month. Should be fixed in 2.0.0
