### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by festro** [Insane96/EnhancedAI#119]
**Describe the bug**  
The game crashes on startup folowing the latest update

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.3.2
 - Enhanced AI: 1.8.4
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   load game
2.   crash
3.   

**Screenshots**  

**Logs**  

[crash-2023-10-30_15.49.12-fml.txt](https://github.com/Insane96/EnhancedAI/files/13210407/crash-2023-10-30_15.49.12-fml.txt)

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
not tested

**Comment by Insane96** [comment]
Reproduce this with few mods as possible. There's a reason the "Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?" question is there.

**Comment by festro** [comment]
It's fine I just downgraded to 1.8.3 and it's working just fine, I've got 151 mods in this pack and would rather avoid playing whack a mole until curse implements a mass enable\disable switch.
