### ISSUE TITLE
[Suggestion] Monsters can break boats / minecarts they're trapped in

### ISSUE THREAD

**Issue by SandwichHorror** [Insane96/EnhancedAI#12]
**What is this?**
Some kind of mechanic that prevents or counteracts the common strategy of trapping any and all monsters in boats and minecarts, rendering them defenseless and immobile. It doesn't matter how dangerous the creeper or zombie is if it gets incapacitated by a wall of boats. Even an illager raid, buffed with the help of 5 mods, are no match for falling into a boat and remaining there politely until their deaths. 

(Method 1) I think the best and easiest way for this feature to be implemented is through blacklists. Blacklisted mobs would not be able to mount any blacklisted entities. By default the blacklisted mobs would include all vanilla hostile mobs, and the blacklisted entities would include minecraft:boat and minecraft:minecart. 

(Method 2) If this seems too automatic or OP in some way, or does not fully capture your intention of the "AI" part (as a simple mount-cancelling event), then a less powerful alternative would be to add a task to defined mobs to break or attack blacklisted entities they are mounted on.

Where (1) would allow a zombie to walk through a field of boats without trouble, (2) would see the zombie getting "trapped" in the boat, quickly breaking the boat and destroying the entity, and continuing its path, repeating for each boat in its way. 

(2) seems to be more troublesome to implement for entities that lack melee attacks, and to me it's stupid that any monster would actually be trapped by an immobile vehicle in any way. 

Full disclosure: this feature is directly inspired by a 1.12 mod I planned and commissioned called Rebirth of the Mobs. (https://github.com/Quarris/RebirthOfTheMobs).

That mod is open source and includes several features that as far as I know, never existed in any other mod across Minecraft history, all for the purpose of increasing difficulty and "fair play" against monsters while allowing extensive modpack customization of entities. There's no equivalent like it for 1.16, and while monsters & minecarts aren't _directly_ related to AI tasks, I think the addition of the mount-cancelling/counteracting feature, even if it's off by default, would be a definite boon for Enhanced AI. 

I think most people who use your mod use it for tougher mobs in general. Keeping the vanilla vehicle-trap mechanic not only conflicts with the overall goal of Enhanced AI, but it makes the incongruity glaringly obvious and perhaps even encourages this cheese: because mobs are now so much more challenging and now even pose a threat to your walled structures, why not effortlessly pacify them and protect your base with this one easy trick? 

Thanks for coming to my TED talk.

**Comment by Insane96** [comment]
I think I will try to implement 2. Most mobs have melee attack (even skeletons that wield a bow). For creepers ... well, their only solution is to blow up

**Comment by Insane96** [comment]
Method 1 was much much easier

**Comment by kristibektashi** [comment]
> I think I will try to implement 2. Most mobs have melee attack (even skeletons that wield a bow). For creepers ... well, their only solution is to blow up

I believe method 2 should exist as a config option

**Comment by Insane96** [comment]
That would be fun

**Comment by Insane96** [comment]
Well, it took me just two years
