### ISSUE TITLE
Enhanced Ai (enhancedai) has failed to load correctly

### ISSUE THREAD

**Issue by Cohzey** [Insane96/EnhancedAI#121]
I downloaded the correct versions of InsaneLib and EnhancedAi, but it won't load correctly.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.3.2
 - Enhanced AI: 1.8.4
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   
2.   
3.   

![image](https://github.com/Insane96/EnhancedAI/assets/149563213/7604732a-5488-4b59-8464-8df22b4abe89)

Latest Log: https://pastebin.com/MQ6rFQ1y
Crash Report: https://pastebin.com/7XTNiZLL

I have it with a big modpack, list of mods;
https://pastebin.com/2NgEYbPi

**Comment by Cohzey** [comment]
I might have found a solution,, trying to see if the enhanced ai version is the problem. I'll try to downgrade to lower version from 1.8.4 to 1.8.3 and see if it does anything.

**Comment by Cohzey** [comment]
![image](https://github.com/Insane96/EnhancedAI/assets/149563213/65763c2a-a6ed-4893-98b0-52f47f2fdd38)

the problem was the EnhancedAi version which was 1.8.4 (fix was downgrading to 1.8.3)
No wonder that version had so little downloads from players! Anyway.. I LOVE WHAT YOU DO! KEEP DOING IT! HAVE A WONDERFUL DAY/NIGHT!

**Comment by Insane96** [comment]
Please don't close issues that are still an issue

**Comment by Insane96** [comment]
Something went wrong in the building process, I've reuploaded 1.8.4 and should now work.
