### ISSUE TITLE
Invalid entity rotation: NaN, discarding.

### ISSUE THREAD

**Issue by Minedoll** [Insane96/EnhancedAI#122]
**Describe the bug**  
If a skeleton (or any other skeleton type mob with a bow) fires an arrow at a mob it is riding, the server will stop.
[Server thread/ERROR] [net.minecraft.Util/]: Invalid entity rotation: NaN, discarding.
[Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

After several tests, I found that this issue is related to the following options
skeleton-> skeleton shoot-> arrow inaccuracy

This does not happen with "Enable Skeleton Shoot" = false or "Arrow Inaccuracy" = 0.0

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft:  1.19.2
 - Forge:  43.2.23
 - Enhanced AI: EnhancedAI-1.8.4-mc1.19.2
 - InsaneLib: 1.7.5-mc1.19.2

**Steps to reproduce**  
1.   Summon "any mob ridden by a skeleton (or any other skeleton type mob with a bow)"
2.   If for some reason the skeleton fires an arrow at the mob it is riding, the server will stop.
**Screenshots**  
![2023-11-14_17 50 02](https://github.com/Insane96/EnhancedAI/assets/150786532/02773eb2-fa77-4002-8eb0-6574d1f4d748)

video-> https://www.youtube.com/watch?v=rtf6hXHiXpQ

**Logs**  
https://pastebin.com/JPAznf55

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes
But for ease of reproduction, the video above uses the mob battle mod

**Comment by Minedoll** [comment]
After further testing, I found a way to reproduce the issue using only enhanced ai
But since it is difficult to explain in writing, please refer to the following video
https://www.youtube.com/watch?v=CRCfp4SyBq4

From the above video, this issue is considered to occur when a skeleton mounted on a mob looks down and shoots an arrow
(and all other mobs affected by the skeleton shoot option)

**Comment by Insane96** [comment]
Does this happen in vanilla?

**Comment by Minedoll** [comment]
It did not happen in vanilla or forge only
It only happens when enhanced ai is installed and "skeleton shoot" option is true

**Comment by Insane96** [comment]
Fixed in 1.8.5 for 1.19.2 and next update for 1.20.1
