### ISSUE TITLE
Latest Enhanced Ai 1.19.2 seems to crash on InsaneLib 1.7.5

### ISSUE THREAD

**Issue by aghostofstarman255** [Insane96/EnhancedAI#125]
It works with the previous version of InsaneLib 1.7.4.
Tested without any other mods.

Crash Log here
[latest.log](https://github.com/Insane96/EnhancedAI/files/13468642/latest.log)

**Comment by aghostofstarman255** [comment]
Actually I got it to work for some reason I have no idea what I changed?

**Comment by aghostofstarman255** [comment]
Well nevermind made a new profile now its doing it again??

**Comment by Insane96** [comment]
You're missing InsaneLib

**Comment by Insane96** [comment]
Your CF might be corrupted, it says that there is no insanelib, but it's loaded

**Comment by Insane96** [comment]
No more reply. Closing
