### ISSUE TITLE
1.20.1 No longer able to blacklist vision range or xray on certain mobs?

### ISSUE THREAD

**Issue by Lerrycapetime** [Insane96/EnhancedAI#127]
This line is nowhere to be found and it was extremely helpful on preventing certain mobs like Mutant Creeper or Cave Dwellers from targeting the player from far away. Mod version is 2.0.5 latest everything.

		#Entities in here will not be affected by this feature.
		[Base.Targeting."Entity Blacklist"]
			Blacklist = ["mutantmonsters:mutant_creeper", "cave_dweller:cave_dweller"]
			#If true the list will be treated as a whitelist instead of blacklist
			"List as Whitelist" = false

**Comment by Insane96** [comment]
You must use Entity Type tags since 2.0. Check the wiki here on github
