### ISSUE TITLE
Zombie Miner causing java.lang.IndexOutOfBoundsException: 

### ISSUE THREAD

**Issue by Poke024** [Insane96/EnhancedAI#128]
**Describe the bug**  
The miner's BlockBreakerGoal, canHarvestBlock method is somehow causing an IndexOutOfBoundsException.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.2.6
 - Enhanced AI: 2.0.3
 - InsaneLib: 1.12.1

**Steps to reproduce**  
1.   Load server.
2.   ?????????
3.   Miner zombie spawns and decides today is a great day to check if it can harvest a block.
4.   Crashes the server.

**Logs**  
https://pastebin.com/TPHJ0EvS

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Unknown. It's up to the universe if it wants to spawn a Miner zombie and crash the game.

**Comment by Poke024** [comment]
Should've added, this was on the Craft to Exile 2 modpack. Let me know if this issue occurring in a modpack means I should redirect the issue submission elsewhere.

**Comment by Insane96** [comment]
This is strange. I will check it.

**Comment by Insane96** [comment]
Oh wait. Update to a newer version
