### ISSUE TITLE
minecraft doesn t work correctly

### ISSUE THREAD

**Issue by Imayreportbugs** [Insane96/EnhancedAI#13]
**Describe the bug**

**Versions:**
 - Minecraft: 1.16.6
 - Forge: 36.2.0
 - Progressive Bosses: 
 - InsaneLib: 1.2.1

**Steps to reproduce**
1. install the latest update
2. launch the game
3. the menu is broken

**Expected behavior**
Able to play singleplayer, multiplayer and see the correct letters

**Screenshots**
![image](https://user-images.githubusercontent.com/85785009/131912485-f28c4355-2277-4714-9453-166fc2553d1d.png)

**Logs**
[2021-09-02-6.log.gz](https://github.com/Insane96/EnhancedAI/files/7101640/2021-09-02-6.log.gz)
[crash-2021-09-02_22.27.20-client.txt](https://github.com/Insane96/EnhancedAI/files/7101643/crash-2021-09-02_22.27.20-client.txt)

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**

- Yes/No

**Comment by Insane96** [comment]
You didn't answer the questions.

**Comment by Gaviell** [comment]
This appears to be the same issue I had. Go into Enhanced AI's config file and change where it says "24, 48" for the skeleton shooting to "24,48" (remove the space).
