### ISSUE TITLE
Digger Zombie causes a IndexOutOfBoundsException error and crashes my server

### ISSUE THREAD

**Issue by Shiumee** [Insane96/EnhancedAI#133]
**Describe the bug**  
The digging zombie seems to cause an IndexOutOfBoundsException error when trying to harvest a block and ends up ticking out the server, causing it to crash.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.18.2
 - Forge: 40.2.14
 - Enhanced AI: 1.6.10
 - InsaneLib: 1.5.3

**Steps to reproduce**  
1.   Launch Forge 1.18.2
2.   Exist on a server
3.   Crash

**Logs**  
Crash log = https://pastebin.com/NVhN4Jzi

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

**Comment by Shiumee** [comment]
I have since then just entirely disabled digger zombies, but I would like to not have to do this

**Comment by Insane96** [comment]
Fixed in 1.6.11
