### ISSUE TITLE
Miner pillagers'AI breaks down

### ISSUE THREAD

**Issue by betterworld-sjq** [Insane96/EnhancedAI#135]
For pillager miners, they would act like their AI is broken, stand still and do nothing else. But when you came close enough to their face, their AI would restart and reloading their crossbows, until you move a little bit farther, their AI would then stop again.Don't know whether this happens to all ranged mobs.
 - Minecraft: 1.20.1
 - Forge: 47.0.0
 - Enhanced AI: 2.2.0
 - InsaneLib: 1.12.1

**Comment by Insane96** [comment]
Sadly ranged mobs don't work properly for mining. There's not much I can do to fix this.

**Comment by Insane96** [comment]
Still, next update they will atleast mine
