### ISSUE TITLE
"Attack When Avoiding" problem for pillagers

### ISSUE THREAD

**Issue by betterworld-sjq** [Insane96/EnhancedAI#136]
With latest version of EnAI and InsaneLib, forge 1.20.1;
Pillagers with "Attack When Avoiding" AI would only flee once, but right then they stop and stand to shoot me continuously no matter how close I am, seeming like their attacking will take over the fleeing will entirely.

**Comment by Insane96** [comment]
Nice catch. They will now flee when uncharged or charging the crossbow and will stop to shoot
