### ISSUE TITLE
spider web issue when being thrown

### ISSUE THREAD

**Issue by stiizmachine** [Insane96/EnhancedAI#138]
whenever the spider throws a web at me the player gets stuck. Well obviously but it causes the player to glitch an incapable of moving compared to being stuck in a minecraft:spider web

**Comment by Insane96** [comment]
There's a reason there's a template with infos needed. Open a new issue and follow that. Also the spider web's only slow down players, they don't place a web if an entity is hit

**Comment by stiizmachine** [comment]
i know that, its just whenever a spider throws a web it doesn't act like a normal minecraft:web. It doesn't slow me down it just makes me completely stagnant incapable of moving until it despawns. Also i tried editing the config but it didnt seem like any changes applied.
