### ISSUE TITLE
Spider web bug (redo)

### ISSUE THREAD

**Issue by stiizmachine** [Insane96/EnhancedAI#139]
**When spider throws web - causes player to be perpetually stuck(not slowed) until web despawns. Moving in any direction sends character back to original position within the web.**  

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.37
 - Enhanced AI: 1.8.5
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   place spider in survival
2. wait for it to shoot web
3.   
4.   

**Screenshots**  
Only video evidence would be sufficient enough but i dont believe it will allow me to put that on here.
[latest.log](https://github.com/Insane96/EnhancedAI/files/14131082/latest.log)

**Logs**  
Use a paste site (**pastebin, gist**) to send the game logs (both logs and crash if applicable)  
For the love of god, don't paste the logs here

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes/No
Yes can be reproduced with enhanced ai idk what a minimal set of mods is.

**Comment by Insane96** [comment]
> Yes can be reproduced with enhanced ai

Can be reproduced with EnhancedAI **ONLY**?

**Comment by Insane96** [comment]
Seems like this has nothing to do with Enhanced AI
