### ISSUE TITLE
Crash on launch with Enhanced AI 1.1.1

### ISSUE THREAD

**Issue by Gaviell** [Insane96/EnhancedAI#14]
**Describe the bug**
Game crashes on launch with the most recent versions of Enhanced AI and Insane Lib installed.

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Progressive Bosses: 
 - InsaneLib: 1.2.1

**Steps to reproduce**
1. Launch game with only Enhanced AI and InsaneLib installed.

**Expected behavior**
Game doesn't crash.

**Screenshots**

**Logs**
https://pastebin.com/sq6Jt1NB

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes

**Comment by Insane96** [comment]
Fixed in the next update (releaaed in a few days hopefully). In the meantime, go in the config and change the Min Max Shooting Range from 24, 48 to 24,48 (basically remove the space).

**Comment by Gaviell** [comment]
This fixed it. Thank you.
