### ISSUE TITLE
Mod Incompatibility with various infection mods such as The Hordes, Spore, From Another World, and Sculk Horde

### ISSUE THREAD

**Issue by Daralexen05** [Insane96/EnhancedAI#143]
**Describe the bug**  
Witches with Enhanced AI-enabled will throw potions that buff hostile mobs in hopes of being able to kill their targets more easily. This works just fine with vanilla and most PVE-oriented mods, but this makes them sitting ducks for Zombies, infected, Sculked, and Things from Hordes, Spore, Sculk Horde, and From Another World. Witches will still attempt to buff and stay close to these mobs, even if they are being attacked by them. I can do further testing with Zoglins, Johnny Vindicators, and The Wither if this problem persists with Witches attempting to buff mobs that want to kill them.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Enhanced AI: EnhancedAI-2.0.5-mc1.20.1.jar
 - InsaneLib: InsaneLib-1.12.1-mc1.20.1.jar

**Steps to reproduce**  
1.   Install The Hordes, From Another World, or Fungal Infection: Spore alongside Enhanced AI
2.   Spawn a Witch any Vanilla Zombie or any aggressive mob from Spore or From Another World
3.  Watch as the Witch tries to buff their aggressor and transform into a Zombie Witch, Infected Witch, or The Thing in the process.  

**Screenshots**  

**Logs**  
Use a paste site (**pastebin, gist**) to send the game logs (both logs and crash if applicable)  
For the love of god, don't paste the logs here

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
No

**Comment by Insane96** [comment]
Enhanced AI doesn't make witches buff mobs (yet)

**Comment by Daralexen05** [comment]
> Enhanced AI doesn't make witches buff mobs (yet)

Thank you for the clarification. This is in a modpack not made by myself. I am not sure which mod is causing Witches to buff mobs. There are some other strange AI issues as well such as mobs not fighting back against Zombies or Spore mobs, but now I know that it is another mod.
