### ISSUE TITLE
The "bite" feature is activated when you attack with guns of Vic's Point Blank.

### ISSUE THREAD

**Issue by Titodelo** [Insane96/EnhancedAI#144]
**Describe the bug**  
The feature should only activate when you attack without weapons, however when you shoot at any distance with a gun at a zombie with the Vic's Point Blank mod

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.2.19
 - Enhanced AI: 2.3.1
 - InsaneLib: 1.12.1

**Steps to reproduce**  
1.  Install Vic's Point Blankc: 1.0.2 & GeckoLib: 4..4.2
2.  Fire to a zombie!
3.  Take the damage

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

I don't know if the bug comes from here or from some incompatibility with VICS, just in case I'm publishing it in both (and sorry for my Google translate).

**Comment by Insane96** [comment]
This is a bug on their end. The feature checks if the direct entity of the hit is a living entity. For some reasons their projectile of whatever returns the player? 
They don't even have a source, so there's nothing I can do
