### ISSUE TITLE
Mobs get stuck in caves underneath the player, causing severe collision and AI (?) lag

### ISSUE THREAD

**Issue by Barerock** [Insane96/EnhancedAI#147]
**Describe the bug**  
Mobs, when they cannot reach the player, will often congregate in closed off sections underneath the player. This causes severe lag related to collision and I suspect also their AI trying to path incorrectly. This lag reduces FPS from 90+ to 20-30 when facing the direction of the mobs. I've noticed this extensively now and each instance of lag can be linked directly to a clogged up mass of maybe 5-15 mobs in a cave underneath me. Setting the game to peaceful and letting everything load back in will completely eliminate the issue until mobs manage to path nearer and clump up again.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Enhanced AI: 2.3.1
 - InsaneLib: 1.13.1

**Steps to reproduce**  
1. Difficulty: Hard
2. Play in survival during any time, but most effectively during day
3. Run around, do stuff, whatever, in one area for anywhere from 10 minutes to an hour
4. Eventually, an area will present far more FPS droppage than normal, starting in the 40s, then graduating to the 30s and 20s minutes after
5. Set spectator mode and look around that area for mobs clumped together. Sometimes as many as 15 or 20.
6. Reset monsters via Peaceful, repeat.

**Logs**  
[latest.log](https://github.com/Insane96/EnhancedAI/files/14553290/latest.log)

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
I don't have the time currently and wanted to write this down in a proper report, but I will test this tomorrow and get back. I have noticed Enhanced AI clumping before, although the lag response wasn't nearly as bad due to the limited cave structures underneath where my player activity was. In fact, I lived on an artificial mountain I hand filled with stone, so NO mobs could spawn in trapped areas anywhere near my player. I think precedence allows for some leeway with testing this immediately, again, I'll get back with this.

In the meantime, if any immediate mod incompatibilities are noticed, I will remove and test those with the isolated test instance. I love this mod, I really hope it isn't the issue, but also this has been causing anguish for some time, so... double sided sword.

<3

**Comment by Insane96** [comment]
No updates with Enhanced AI only, closing
