### ISSUE TITLE
[1.20.1] Enhanced AI trying to cast Non-Mob-Subclass as Mob

### ISSUE THREAD

**Issue by FCWYzzr** [Insane96/EnhancedAI#148]
**Describe the bug**  
EAI trying to cast Naga Segment from Mod Twilight Forest (class twilightforest.entity.boss.NagaSegment) to Mob (class net.minecraft.world.entity.Mob), causing minecraft to crush.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Enhanced AI: 2.3.1
 - InsaneLib: 1.13.1
 - Twilight Forest 4.3.2145

**Steps to reproduce**  
1.   install TF, IL & EAI
2.   enter game & enter twilight forest 
3.   at the time of rending Naga, the game crushed

**Screenshots**  
Game crushed at the time of rending Naga Segment.

**Logs**  
crush report (fragment)

    java.lang.ClassCastException:
    class twilightforest.entity.boss.NagaSegment cannot be cast to class net.minecraft.world.entity.Mob (...NagaSegment is in xxxx, ...Mob is in module xxxx)
    at....

file:
[crash-2024-03-12_15.59.59-client.txt](https://github.com/Insane96/EnhancedAI/files/14597406/crash-2024-03-12_15.59.59-client.txt)

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Twilight Forest & EAI only

**Comment by Insane96** [comment]
Send the crash with TF and EAI only, because seems like EAI has nothing to do with this

**Comment by Insane96** [comment]
No follow up, closing
