### ISSUE TITLE
Digger Zombie causing java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Fruziz** [Insane96/EnhancedAI#153]
**Describe the bug**  
The digger zombie DiggingGoal.canHarvestBlock causing IndexOutOfBoundsException

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.3.9
 - Enhanced AI: 1.8.5
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   Join the world
2.   wait for a digger zombie to spawn
3.   Game crash

**Logs**  
https://pastebin.com/DYgB4dHq

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
In the logs there's the OnlyLooking mod, maybe you need it.

**Comment by Insane96** [comment]
Fixed for next update
