### ISSUE TITLE
Crash mohist server

### ISSUE THREAD

**Issue by XionioXMaster** [Insane96/EnhancedAI#16]
**Describe the bug**

**Versions:**
 - Minecraft: 1 16 5 mohist 764
 - Forge: 36.2.4 - Enhanced AI: 1 1 1
 - InsaneLib: 1.2.1

**Steps to reproduce**
1. No idea

**Screenshots**

**Logs**
https://mclo.gs/Xws4yBp

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
No idea

**Comment by Insane96** [comment]
You still didn't answer the questions ...
