### ISSUE TITLE
[1.19.2] Zombie with digger AI does not mine/break chests and barrels

### ISSUE THREAD

**Issue by Viktordrr4** [Insane96/EnhancedAI#160]
**Describe the bug**  
Zombie with digger AI does not mine/destroy barrels and chests (tile blocks I believe). Also tested with whitelist blocks on and only including barrel and chest.
All of the mods used for the report is cloth-config, configured , enhancedai, insanelib.

How I encountered it,
First noticed this when my base made of Domum Ornamentum blocks were not getting mined but other blocks were. Tested with those blocks first and some furnace blocks from other mods and noticed that they did not get mined. Then tried with chests and such before creating a new instance of minecraft with only the mods listed above.

**Versions where you encountered the problem:**  
 - Minecraft: 1.19.2
 - Forge: 43.3.13
 - Enhanced AI: 1.8.6
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   Set digger chance to 1 and to spawn with wooden pickaxe true to see if it is a digger zombie.
2.   Blacklist tile entities false.
3.   Surround a zombie in a box of barrels or chests.
4.   Make some of the blocks breakables such as cobble and glass.
5.   Zombie does not break the barrels and chests.

**Screenshots**  
https://imgur.com/a/Dptj0Z6

**Logs**  
Log https://pastebin.com/0BHJpSUK
Enhanced AI Config https://pastebin.com/6dVtA2gd
InsaneLib Config https://pastebin.com/YQiP6LrC

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

**Comment by Insane96** [comment]
Fixed in next release

**Comment by Viktordrr4** [comment]
Thank you!
Now both chests, barrels and the blocks from Domum Ornamentum work as expected and without any problems.
