### ISSUE TITLE
设置某方块不允许破坏无效

### ISSUE THREAD

**Issue by vdjango** [Insane96/EnhancedAI#161]
**Describe the bug**  
设置某方块不允许破坏无效

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.18.2
 - Forge:  40.2.18
 - Enhanced AI: EnhancedAI-1.6.11-mc1.18.2
 - InsaneLib:  InsaneLib-1.5.3-mc1.18.2.

**Steps to reproduce**  
1.   修改配置文件  config\enhancedai\common.[Mobs]....[Mobs."Miner Mobs"."Dimension Blacklist"]
2.   添加方块ID Blacklist = ["minecraft:smooth_stone"]
3.   僵尸依然会破坏 minecraft:smooth_stone 方块，

**Comment by Insane96** [comment]
English only please
