### ISSUE TITLE
I'm slow how does this work

### ISSUE THREAD

**Issue by Sirenamogus** [Insane96/EnhancedAI#162]
**Describe the bug**  
The bug is that I'm stupid and can't figure out how to (or if I even can) set mobs from other mods to have miner functionality. (the ability to spawn as miners and be able to mine towards the player)
**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.20.1
 - Forge: 47.2.32
 - Enhanced AI: 2.4.7
 - InsaneLib: 1.13.4

**Steps to reproduce**  
1.   -be me
2.   -try to make a horde survival modpack
3.   -can't figure it out and I have to ask for help

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

**Comment by Insane96** [comment]
Use data packs. Also use discord for help next time
