### ISSUE TITLE
TPS 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [Insane96/EnhancedAI#163]
EnhancedAI-2.4.7-mc1.20.1.jar

Without adding a mod
![image](https://github.com/Insane96/EnhancedAI/assets/106809386/e7cba464-48f7-44ae-812c-990a0699d19e)
![image](https://github.com/Insane96/EnhancedAI/assets/106809386/01999dec-d123-484c-b833-81b686495781)
With the mod, there is a miscalculation of intelligence, apparently
![image](https://github.com/Insane96/EnhancedAI/assets/106809386/a7c680b1-8688-4d04-ad78-a79174cde2c7)
TPS is stabilizing, but remains too high, while not all mods are added
![image](https://github.com/Insane96/EnhancedAI/assets/106809386/c27c7996-03a6-47fc-ad40-e36cdc165de3)

Are there any ways to influence the TPS of this mod? Maybe it can be fixed?

Spark
![image](https://github.com/Insane96/EnhancedAI/assets/106809386/8d84b55e-9dd7-447d-b025-898c10fcca5e)
Spark tick over 50
![image](https://github.com/Insane96/EnhancedAI/assets/106809386/710d2aad-2c62-4caa-89aa-7549a662a2f3)

**Comment by Insane96** [comment]
Have you tested with Enhanced AI only as the template you ignored told you?

**Comment by Krimatoria** [comment]
> Проводили ли вы тестирование только с использованием улучшенного ИИ, как и говорилось в шаблоне, который вы проигнорировали?

I'm going to do a big test with mods today to understand the impact on TPS. Since intelligence is associated with mobs, it is possible that this is some kind of conflict with another mod that creates certain creatures. 

The Spark test can somehow help you in understanding the impact of TPS if I find some kind of dependence, I'm just not strong in understanding Spark, can you tell me what you can pay attention to? 

I will run the build one at a time, first I will add intelligence, and then all the mods for creatures and only then everything will be over again with the rest of the mods, it will be a long process.

**Comment by Insane96** [comment]
If you have many mods just disable the "avoid" stuff for skeletons, pillagers, witches and animals

**Comment by Krimatoria** [comment]
> Если у вас установлено много модов, просто отключите функцию «избегать» для скелетов, грабителей, ведьм и животных.



> Если у вас установлено много модов, просто отключите функцию «избегать» для скелетов, грабителей, ведьм и животных.

Is it here?
![image](https://github.com/user-attachments/assets/a9ec3893-ee63-4390-adb8-d52f82db50b1)

**Comment by Insane96** [comment]
Yes. Or just search in the file

**Comment by Krimatoria** [comment]
> Да. Или просто поищите в файле

I figured it out, it turns out that the TPS drop was not directly related to your mod) It was influenced by another mod)
