### ISSUE TITLE
Crash on 1.20.1 forge

### ISSUE THREAD

**Issue by NotTohm** [Insane96/EnhancedAI#165]
https://paste.ee/p/49gtk

**Comment by Insane96** [comment]
First off: you deleted the template without following it so that's an instant close
Second: The crash doesn't mention EnhancedAI anywhere
Third: stop using shitty mccrator mods

**Comment by NotTohm** [comment]
the fuck? check the head category, it says "suspected mods: enhanced ai". and i closed the template cuz theres nothing else to be said

**Comment by Insane96** [comment]
It's literally in the first rows. Enemy expansion, an Mccreator mod.
As said: no template no party.

**Comment by NotTohm** [comment]
alright, ill report it to them instead since the crash is prob cuz of them anyway
