### ISSUE TITLE
Creeper breaching not working correctly / Surrounding zombies being aggro'd upon one getting hit.

### ISSUE THREAD

**Issue by 4zy1** [Insane96/EnhancedAI#166]
Creepers will not explode to breach if the player has dug a hole and placed a block above them, sometimes the Creeper will ignite as if they're about to explode, but never will, and most of the time they just never ignite at all. And zombies have an issue where if you shoot/hit a single zombie, all surrounding zombies will get aggroed, even with all settings off/set to their lowest.

 - Minecraft: 1.20.1
 - Forge: 47.3.5
 - Enhanced AI: 2.4.2
 - InsaneLib: 1.13.5

https://github.com/user-attachments/assets/e623bb09-1b66-4b24-a113-ef67a949d101

https://github.com/user-attachments/assets/b1589af3-a22b-4582-b4ae-43ebd47ad0d5

**Comment by 4zy1** [comment]
Here's my config file if that helps, I uploaded it as a .json since .toml's can't be uploaded here.

[common.json](https://github.com/user-attachments/files/16745506/common.json)

**Comment by Insane96** [comment]
Please use the latest version

**Comment by 4zy1** [comment]
> Please use the latest version

This still happens on the latest version, I tried this on the latest one first than downgraded to see if these issues were caused by an update.

**Comment by Insane96** [comment]
Will take a look.

> And zombies have an issue where if you shoot/hit a single zombie, all surrounding zombies will get aggroed, even with all settings off/set to their lowest.

This is vanilla, idk what setting you're talking about

**Comment by Insane96** [comment]
The creepers stop because you disabled the targeting feature. Vanilla mobs stop targeting you they can't see you for 2 or so seconds
