### ISSUE TITLE
[enhancement request] Add config option to disable fisher mobs stealing from your inventory

### ISSUE THREAD

**Issue by joshmcorreia** [Insane96/EnhancedAI#174]
I'd love it if you could add a config option to disable fisher mobs stealing from your inventory. It looks like the issue that added this was https://github.com/Insane96/EnhancedAI/issues/112. Thank you!

**Comment by Insane96** [comment]
There's a chance that you can set to 0 already

**Comment by joshmcorreia** [comment]
Oh thank you, my friend was the one editing the config and missed the hookInventoryChance. Great mod, thanks!
