### ISSUE TITLE
[Suggestion] Base/Targeting Module Entity Blacklist

### ISSUE THREAD

**Issue by SandwichHorror** [Insane96/EnhancedAI#2]
**What is this?**
A blacklist where listed entities will not receive any of the base/universal targeting modifications.

**Why?**
A blacklist is more or less essential if this mod is to be used with other mods that add new entities. Many modded mobs have unique AI or methods of targeting and player detection that are likely to be incompatible with Enhanced AI. The blacklist would prevent these conflicts from occurring in the first place. Even without other mods, a player may wish to prevent a specific vanilla mob from gaining the new targeting features, and the blacklist could make that possible. 

Here's a very crude mockup of something similar to the requested blacklist feature.
https://i.imgur.com/31Ov346.png

**Comment by Insane96** [comment]
Added in 1.0.0
