### ISSUE TITLE
A bunch of suggestions

### ISSUE THREAD

**Issue by EthanDSYT** [Insane96/EnhancedAI#25]
- [x] Configurable spider web lifetime, damage, minimum/maximum range, and cooldown
- [x] Blacklist/whitelist mobs that avoid creeper explosions (or maybe alternatively different modes, like hostiles only, passives only or all)
- [Nope] Grant digger zombie's ability to break blocks with x seconds (configurable) delay after spawning (honestly this is just a minor quality of life tweak, and it'd help a slight compatibility issue I have with the datapack spawn animations that make hostiles spawn underground and dig their way up, as of now it makes them dig into the floor half the time)
- [ ] Make digger zombie's stop digging if they can't reach their goal within like x blocks (configurable)
- [Use vanilla commands or mods like MobsPropertiesRandomness] Configurable launcher creeper's attack damage (personally I'd weaken the damage and increase the percentage of launcher creepers to correspond)
- [Not in the scope of the mod] Add an option to for the ability to pick up skeleton arrows (as a config, maybe even with a maximum limit per skeleton to prevent farming)
- [x] Digger zombie block blacklist/whitelist, or *alternatively* a block hardness value range requirement (only dig easy to break blocks) e.g, to prevent them mining obsidian bare handed

**Comment by EthanDSYT** [comment]
Wrong label lol, sorry, new to GH

**Comment by Insane96** [comment]
> Configurable launcher creeper's attack damage

What do you mean by that?

**Comment by EthanDSYT** [comment]
> 
When they explode they deal less damage

**Comment by Insane96** [comment]
Just increase their explosion radius with other mods like Mobs Properties Randomness.

**Comment by Insane96** [comment]
> Grant digger zombie's ability to break blocks with x seconds (configurable) delay after spawning

The AI has been changed, they should take 3 seconds to start mining now
