### ISSUE TITLE
List of suggestions

### ISSUE THREAD

**Issue by EthanDSYT** [Insane96/EnhancedAI#26]
-Configurable spider web lifetime, damage, minimum/maximum range, and cooldown
-Blacklist/whitelist mobs that avoid creeper explosions (or maybe alternatively different modes, like hostiles only, passives only or all)
-Grant digger zombie's ability to break blocks with x seconds (configurable) delay after spawning (honestly this is just a minor quality of life tweak, and it'd help a slight compatibility issue I have with the datapack spawn animations that make hostiles spawn underground and dig their way up, as of now it makes them dig into the floor half the time)
-Make digger zombie's stop digging if they can't reach their goal within like x blocks (configurable)
-Configurable launcher creeper's attack damage (personally I'd weaken the damage and increase the percentage of launcher creepers to correspond)
-Add an option to for the ability to pick up skeleton arrows (as a config, maybe even with a maximum limit per skeleton to prevent farming)
-Digger zombie block blacklist/whitelist, or alternatively a block hardness value range requirement (only dig easy to break blocks) e.g, to prevent them mining obsidian bare handed

**Comment by EthanDSYT** [comment]
Holy crap. Ffs why is this so difficult to use? How the hell do I use labels

**Comment by Insane96** [comment]
You can't use lables. Only the repo owner can use lables. Label is set automatically for bug reports. I have to manually set other labels.
Gonna edit the original post and reopen it.
