### ISSUE TITLE
[Suggestion]  Please make the Nether more dangrous!

### ISSUE THREAD

**Issue by blood789** [Insane96/EnhancedAI#27]
[Suggestion]  Please make the Nether more dangrous!
Version：1.16.5
Several enhanced AI/difficulty suggestions for Zombified Piglin, one of the most forgettable Minecraft mobs.

The Nether is too safe for players now.
- [ ] Hostile Zombified Piglin instead of neutral.
- [ ] Allow the Ghast to fire multiple fireballs at once and control the firing speed.
- [x] Make all the monster in The Nether spawn with XRay. They'll be able to target players even if they can't see them.

**Comment by Insane96** [comment]
> 3.Make all the monster in The Nether spawn with XRay. They'll be able to target players even if they can't see them.
This should be already a thing
