### ISSUE TITLE
[Suggestion] Separate Follow Range and X-Ray Ranges

### ISSUE THREAD

**Issue by SandwichHorror** [Insane96/EnhancedAI#3]
**What is this?**
Provide separate configuration for the values of the follow range and x-ray.

**Why?**
Increased follow range is a great feature for many reasons: increased difficulty, greater realism (the zombies across the field can "see" you and chase you accordingly), harder to escape mobs by running away, better "base defense"-style gameplay.

X-Ray is more of a significant change, has a little bit more of a "BS factor" to it, and being able to tweak it separately would be excellent. Allowing mobs to have a follow range of 64, but only an X-ray detection radius of 12 blocks, would ensure mobs could pursue the player, but could be thwarted by thick walls or hiding underground, and would prevent mobs constantly aggroing on you while stuck in a cave deep below you.

I'm unsure of the default X-Ray value in Enhanced AI - is it a fixed internal value, or is it the same as the follow range?
No matter which it is currently, allowing a separate configuration for the range of the X-Ray feature would allow for a significant degree of customization over difficulty.

- Equal follow range and X-Ray: Current settings.
- High follow range, medium X-Ray: Slightly reduced difficulty, more incentive to stealth and building walls
- High follow range, low X-Ray: Reduced difficulty - stealth, obstacles, and building walls become much more valuable

**Comment by Insane96** [comment]
That was something planned when I first started the mod. Adding a separate Attribute for XRay follow range as can be seen here: https://github.com/Insane96/EnhancedAI/blob/master/src/main/java/insane96mcp/enhancedai/setup/ModAttributes.java#L13.
This will allow for better handling of both.
