### ISSUE TITLE
[Suggestion] Mob "Type" Configuration

### ISSUE THREAD

**Issue by SandwichHorror** [Insane96/EnhancedAI#4]
**What is this?**
Configuration of which entities "count" as one of the broad Enhanced AI categories, receiving the same abilities and AI tasks as those vanilla mobs.

**Why?**
To allow greater user customization and compatibility with modded entities. A user could configure husks, modded zombie variants, and other "humanoid"-like mobs to gain the Zombie features. A user could configure entities such as Quark's skeleton variant to gain the Skeleton features.

`# Entities that gain Zombie features [default: ["minecraft:zombie"]]`

**Comment by Insane96** [comment]
This is basically something implemented as Black/Whitelist. The default list will be empty as defaults to blacklist.
