### ISSUE TITLE
1.18.2 crash

### ISSUE THREAD

**Issue by zachsai** [Insane96/EnhancedAI#42]
**Describe the bug**

**Versions:**
 - Minecraft:  1.18.2
 - Forge:  40.1.25
 - Enhanced AI: 1.3.3
 - InsaneLib: 1.4.8

**Steps to reproduce**
1. I do not know
2. 
3. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63996164/171506522-1a23ccf5-a1ae-4421-8f20-3ea8e3e483c0.png)

**Logs**
Use a paste site (pastebin, gist) to send the game logs (both logs and crash if applicable)
https://gist.github.com/WelpSTudent/4d4e0a227fc3ccbcc0b866f5813fdbb5
**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
idk

**Comment by Insane96** [comment]
Probably Villager recruits not registering the knockback attribute to the golem
