### ISSUE TITLE
Game crash when starting

### ISSUE THREAD

**Issue by blood789** [Insane96/EnhancedAI#45]
Game crash when starting~~~

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.1.48----40.1.51
 - Enhanced AI: EnhancedAI-1.4.2-mc1.18.2
 - InsaneLib: InsaneLib-1.5.0-mc1.18.2

**Screenshots**
![QQ截图20220614210501](https://user-images.githubusercontent.com/70810047/173584022-2c6bfe32-3488-42a2-97f0-94e6f3ea15c2.png)

**Logs**
[crash-2022-06-14_20.51.35-fml.txt](https://github.com/Insane96/EnhancedAI/files/8899971/crash-2022-06-14_20.51.35-fml.txt)
[crash-2022-06-14_20.59.41-fml.txt](https://github.com/Insane96/EnhancedAI/files/8899972/crash-2022-06-14_20.59.41-fml.txt)
[crash-2022-06-14_21.01.49-fml.txt](https://github.com/Insane96/EnhancedAI/files/8899973/crash-2022-06-14_21.01.49-fml.txt)
[latest.log](https://github.com/Insane96/EnhancedAI/files/8899981/latest.log)

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
When disabled the EnhancedAI, the game can run and did not crash again

**Comment by Insane96** [comment]
You're not using the latest version of Enhanced AI
