### ISSUE TITLE
witch, problem, crash

### ISSUE THREAD

**Issue by ghost** [Insane96/EnhancedAI#46]
**Describe the bug**
witch, problem, crash
**Versions:*EnhancedAI-1.4.6-mc1.18.2*
 - Minecraft: 1.18.2
 - Forge: 40.1.51
 - Enhanced AI: witch，Skeletons seem to have crashed too
 - InsaneLib: InsaneLib-1.5.1-mc1.18.2

**Steps to reproduce**
1. 
2. 
3. 

**Screenshots**

**Logs**
Use a paste site (pastebin, gist) to send the game logs (both logs and crash if applicable)
[Uploading crash-2022-06-20_23.51.58-client.txt…]()

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes/No
It may be difficult, I load a lot of mods, but I can be sure that there is a problem with (Epic Fight), some of your mods seem to be not very friendly with (Epic Fight); in my report, I have already added ( Epic Fight) was deleted, but there may be problems with other mods, it may be your mod, I don't want to delete your mod, they are excellent.

**Comment by Insane96** [comment]
You uploaded no crash report, use pastebin or gist.gihub.

> It may be difficult,

Also you must test with as low mods as possible

**Comment by Insane96** [comment]
No update in various weeks, closing
