### ISSUE TITLE
Digger AI

### ISSUE THREAD

**Issue by drnoodleguy** [Insane96/EnhancedAI#47]
**Describe the bug**

**Versions**:
* Minecraft:  1.16.5
* Forge: 36.2.34
* Enhanced AI: 1.2.3
* InsaneLib: 1.4.2: 

**Steps to reproduce**
1. Change the zombie AI to always be a digger, and switch between propertoolonly and toolonly.

**Logs**
The game didn't crash, I don't know if this would help.

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
It happened on a custom modpack of 78 mods, but the only mods that I think would cause this issue is big brain (probably not illagers wear armor or friendlyfire).

**Comment by Insane96** [comment]
You didn't describe the bug and you didn't test with a minimal set of mods

**Comment by drnoodleguy** [comment]
The bug is the AI will not dig when tool only setting in the config is selected, but when proper tool only is. I did not test with a minimal set of mods, and when I did I got different results. Zombies would mine planks, hay bales, grass and gravel with proper tool only on, while a digger with a pickaxe would only mine stone if both were false. I dont know the issue, but it is something with the config. The only mods I had were enhanced AI, configured (so I could change the config settings), and insanelib. Technically forge and minecraft (mcp) too.

**Comment by Insane96** [comment]
> I did not test with a minimal set of mods, and when I did I got different results

Make up your mind, did or did you not test with a minimal set of mods? Also if you did and the result is different you must find the mod that gives the problem.

**Comment by drnoodleguy** [comment]
I did not and then I did. Read it.

**Comment by Insane96** [comment]
I don't understand what's your issue then, as I've tested the following options and all work correctly.

With `Digger Tool Only` and `Digger Proper Tool Only` both false, zombies will mine regardless they have a tool or not

With `Digger Tool Only` set to true, zombies will mine only if they have a tool in the off-hand

With `Digger Proper Tool Only` set to true, zombies will mine only if the block requires a tool (e.g. stone) and they have the proper tool for it (in case of stone, a pickaxe). As the config states "Blocks that require no tool (e.g. planks) will be minable regardless of proper tool or not."

**Comment by Insane96** [comment]
No more replies in a month. Closing
