### ISSUE TITLE
After dying to a zombie in a server, pressing the Respawn button crashes the client

### ISSUE THREAD

**Issue by NiciusB** [Insane96/EnhancedAI#48]
**Describe the bug**
After dying to a sworded zombie in a server, pressing the Respawn button crashes the client.

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.1.68
 - Enhanced AI: 1.5.1
 - InsaneLib: 1.5.1

**Steps to reproduce**
Not sure what happened. We died many times without issue, but this one time it crashes my client every time.
I tried restarting the client, but the crash still happens.
I tried restarting the server, and it fixed the issue. I was alive in my spawning point when logging in after restarting the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/2421121/181916103-346c6e29-4b28-4af9-abbd-13f993e7a905.png)

![image](https://user-images.githubusercontent.com/2421121/181916084-f847072f-d939-44c3-b239-13e2bfd8324a.png)

**Logs**
https://crashy.net/eRndlPIhltCZhZRRz5CX

Edit: It happened again with another zombie, this time a baby zombie with a wooden pickaxe. Every time he kills me I crash when respawning https://crashy.net/f5lIyprf8DTzaV8q3r5u
This time, when logging back in I was already alive so didn't get stuck in a crash -> respawn button -> crash loop

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
I assume it could but since it only happened in one specific death it would be hard to reproduce

**Comment by Insane96** [comment]
Update to latest version
