### ISSUE TITLE
[Suggestion] Greater Digger Ability Configuration

### ISSUE THREAD

**Issue by SandwichHorror** [Insane96/EnhancedAI#5]
**What is this?**
Two separate features related to the zombie Digger ability for greater user customization and QOL.

1. Block blacklist
- Zombies can never break blocks or tile entities listed in this blacklist.

2. Require appropriate tool
- Taken straight from the old Epic Siege mod. Mobs can't dig blocks if they don't have the appropriate tool. In most cases, this would allow zombies to break dirt, sand, wood, logs, glass, crops, wool, etc. but not stone and other blocks unless they're holding a pickaxe of the appropriate tier. This allows blocks like obsidian to have greater defensive value in survival mode.

Either the user would use another mod to allow mobs to spawn with pickaxes, or you could create such a feature if you wished. There are already numerous mods that allow mobs to spawn with tools, so I don't think it would be necessary for Enhanced AI to provide this feature. 

`# Digging mobs require the proper tools to dig [default: false]`

**Why?**
Significantly greater customization and QOL. Necessary for large modpacks and user buy-in. Blacklisting expensive machines, or preventing bare-handed zombies from creating immense tunnels through stone 64 blocks away, prevents user frustration while still providing a challenging experience. "Require tool" config would also match nicely with the IguanaTweaks feature that requires the player to wield an appropriate tool to harvest blocks.

**Comment by Insane96** [comment]
Will be in available in next update.
