### ISSUE TITLE
enhanced ai has failed to load correctly

### ISSUE THREAD

**Issue by ALR2310** [Insane96/EnhancedAI#50]
**Describe the bug**
enhanced ai has failed to load correctly

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.1.73
 - Enhanced AI: 1.3.2
 - InsaneLib: 1.5.1

**Steps to reproduce**
1. 
2. 
3. 

**Screenshots**
![image](https://user-images.githubusercontent.com/87233160/183607440-0ba56171-d139-41f4-9b44-d15fcb49fbe9.png)

**Logs**
https://pastebin.com/KSjpPWDB

https://pastebin.com/sfatcfwi

**Comment by Insane96** [comment]
Where did you dowload the mod from? You have a really old version
