### ISSUE TITLE
Xray_follow_range crash on servers/single player. 

### ISSUE THREAD

**Issue by Saereth** [Insane96/EnhancedAI#51]
**Describe the bug**
Crash in Singleplayer or on dedicated server with enhanced AI active having to do with xray_follow_range

**Versions:**
 - Minecraft: 1.18.2
 - Forge:  40.1.73
 - Enhanced AI: EnhancedAI-1.6.0-mc1.18.2
 - InsaneLib: InsaneLib-1.5.1-mc1.18.2

**Steps to reproduce**
1. Unsure, it happens seemingly randomly

**Screenshots**

**Logs**
https://pste.me/v1/paste/jwruXYXu25Y/raw

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes 
Was able to reproduce with a base set of mods, top, jei,

**Comment by Insane96** [comment]
org.cyclops.evilcraft.block.BlockInfestedNether is doing something that prevents their mobs from getting the xray attribute

**Comment by Saereth** [comment]
ok I opened an issue there as well https://github.com/CyclopsMC/CyclopsCore/issues/172

**Comment by rubensworks** [comment]
EvilCraft developer here.

That EvilCraft block is just spawning a Netherfish entity (extension of Silverfish), which registers its attributes like this: https://github.com/CyclopsMC/EvilCraft/blob/02f9152f2e88c595ea5aac42b06318151df85a01/src/main/java/org/cyclops/evilcraft/entity/monster/EntityNetherfishConfig.java#L43-L60

EvilCraft is not preventing attributes from registering.
So I suspect your event handler is just not registering the attribute to this entity?

**Comment by Insane96** [comment]
Was this fixed in EvilCraft?

**Comment by rubensworks** [comment]
Yep
