### ISSUE TITLE
Bug when teleporting with Waystones Mod (Ticking entity fishing rod is null)

### ISSUE THREAD

**Issue by AylanJ123** [Insane96/EnhancedAI#56]
**Describe the bug**
When using a Waystones Mod's Waystone while in the nether after fighting mobs the game crashes. Happens during the process of teleporting because XP is deducted but when returning from crash you are in the first Waystone. Without fighting it doesn't happen, can't reproduce in overworld, but there is a chance that would also happen. Doesn't seem to happen while I am hooked but I think it happens after I get hooked and reeled in. Should I report it to Waystones Mod too?

**Versions:**
Minecraft: 1.18.2
Forge: 40.1.80
Enhanced AI: 1.5.1
InsaneLib: 1.5.1

**Steps to reproduce**

1. Go to nether
2. Fight any zombie-like entity that can use fishing rods
3. Use a Waystones Mod's Waystone to anywhere, game crashes before Waystone teleports you but before it takes your XP, after crash you are where you wanted to teleport, then you can use the Waystone and it won't crash again.

**Screenshots**
Impossible to take one, is inmediate

**Logs**
Nothing appears on the logs resulting from the bug or before the bug. This is the crash report:
https://pastebin.com/wpS0zikd

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Haven't tested it, but log seems to be only for those mods so probably yes

**Comment by Insane96** [comment]
Use the latest version.
