### ISSUE TITLE
【Suggestion】Make animals run smarter

### ISSUE THREAD

**Issue by blood789** [Insane96/EnhancedAI#58]
Version 1.6.4 has a version of minecraft called MITE. In that game, the animal will speed up to escape after being attacked, and it will make the surrounding animals panic and run around. When animals running after being atttack, they do not run in a straight line, and often turn irregularly, making it difficult for players to kill. 

In the current version, if animal counterattack is enabled, killing animals is too easy. Just get up and stand high, and the animals will gather under your feet and kill them slowly.

**Comment by Insane96** [comment]
This has been addressed since the last versions
