### ISSUE TITLE
[Suggestion] Non-zombifying Piglins and Hoglins

### ISSUE THREAD

**Issue by nekomaster1000** [Insane96/EnhancedAI#59]
Adding a config option to change the ratio/turn off Piglin zombifying in other dimensions would be cool! :]
I don't know of another mod that does this, and it could allow for some interesting surprise Overworld encounters!
Would look something like:

[Piglin."No Zombification Chance"]
- [ ] Chance for a Piglin to NOT zombify when in the Overworld
Range: 0.0 ~ 1.0
"No Zombification Chance" = 0.2

Additionally, being able to make Zombified Piglins always hostile would be great, too!

[ZombifiedPiglin."Hostility Chance"]
- [ ] Chance for a Zombified Piglin to be hostile
Range: 0.0 ~ 1.0
"Hostility Chance" = 0.2

**Comment by Insane96** [comment]
This has nothing to do with AI
