### ISSUE TITLE
Digger does not dig blocks higher than two squares

### ISSUE THREAD

**Issue by XM666-Dev** [Insane96/EnhancedAI#62]
**Describe the bug**

Digger does not dig blocks higher than two squares.

![2022-10-31_22 20 57](https://user-images.githubusercontent.com/99076011/199031579-6ddd6ff3-91d1-455c-9c3e-8b0cf6f05896.png)
![2022-10-31_22 22 28](https://user-images.githubusercontent.com/99076011/199031644-4d7297bc-0dea-44c4-94de-c0a44196da46.png)

It does not dig three grid high blocks. It rarely digs three grid high blocks.

But it can normally dig two grid high blocks:

![2022-10-31_22 21 45](https://user-images.githubusercontent.com/99076011/199033082-01c465bb-aec8-4da8-9ac0-a4f27aac0e9b.png)
![2022-10-31_22 22 31](https://user-images.githubusercontent.com/99076011/199033113-de56704a-f64d-4b9d-a1df-9d77f62d5d1b.png)

**Versions:**
 - Minecraft: 1.19.2
 - Forge: 43.1.47
 - Enhanced AI: 1.7.0
 - InsaneLib: 1.7.0

**Steps to reproduce**
As shown in figure.

**Screenshots**

**Logs**
None.

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes.

**Comment by Insane96** [comment]
Not really a bug, the zombie raycasts to the target so if you're right on top of him he doesn't mine blocks below
