### ISSUE TITLE
[Suggestion] Spider Webs Players

### ISSUE THREAD

**Issue by AviumXi** [Insane96/EnhancedAI#65]
Idea: Ability to choose between the player being physically webbed or have slowness applied in the event of being stuck by a spider's webbed projectile. 

As it already exists, slowness is applied when a player is struck and it can easily be disabled in the config so in terms of that side of the equation it is already implemented. (Unless the player is psychotic and wants both slowness AND webbed) 

Background: I prefer the physical webbing style as when in combination with another mod such as "Serilum's Weaker Spiderwebs" the web will break after a second or so after being webbed. However, if the player is quick enough he/she can break the web quickly allowing for a quick escape.

**Comment by stiizmachine** [comment]
yo how were u able to change the config i tried changing it so the spiders are completely off for "false" but they still shooting there webs
