### ISSUE TITLE
[Suggestion] Give Drowned swimming animation and functions

### ISSUE THREAD

**Issue by ZilverLazarus** [Insane96/EnhancedAI#67]
As funny as it is see a Drowned running underwater at Mach 1, I'd appreciate it if you gave us a config option/default upgrade to make Drowned use the player's swimming animation. Not only does it make sense, but this would also allow Drowned to fit into 1x1 spaces while swimming just like the player. 

Hopefully this is considered, and thank you again for making this mod.

**Comment by Insane96** [comment]
Sadly the drowned renderer doesn't support the swim pose. I've added it when swimming but just looks like this
![2022-12-11_10 00 43](https://user-images.githubusercontent.com/7185104/206895133-69a234e8-c96c-4ca1-b931-61c8e4a7587c.png)
