### ISSUE TITLE
Config min/max values may be incorrect, making disabling some things impossible

### ISSUE THREAD

**Issue by Gebcrafter** [Insane96/EnhancedAI#69]
**Describe the bug**
Editing the config (specifically breach and ignore walls creepers) to values anything other than default causes the config to not load properly & generate a bak file.

**Versions:**
 - Minecraft: 1.18
 - Forge: 40.1.86
 - Enhanced AI: 1.6.4
 - InsaneLib: 1.5.1

**Steps to reproduce**
1. Change some value to 0.0, for example, witches "another throw" chance
2. Save the file
3. .bak file appears, and restarting game doesn't load the changed config properly

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes

**Comment by Insane96** [comment]
I need the log. There is written the error

**Comment by Gebcrafter** [comment]
https://pastebin.com/F3JYLZ7v

**Comment by Insane96** [comment]
I need a log when the game creates the backup file

**Comment by Gebcrafter** [comment]
https://pastebin.com/Tt2z5Uxw
this is all i could get. it happens when the game is open and the config is saved again. its impossible to get these changes to stick
for reference, this is the config that is being rejected
https://pastebin.com/6ph7viXp

**Comment by Insane96** [comment]
Are you changing the config while in-game / in a world?

**Comment by Gebcrafter** [comment]
Yes. I've figured out that if I don't edit in-game, it tends to stay fine

**Comment by Insane96** [comment]
Yeah, nightcore doesn't like reloading config while you're in game
