### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by Proxwian** [Insane96/EnhancedAI#70]
**Describe the bug**
Player fighting with Witch caused rare crash. Looks like Witch tried to spawn new mob

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.1.92
 - Enhanced AI: 1.6.4
 - InsaneLib: 1.5.1

**Logs**
[crash-2023-01-04_10.11.50-server.txt](https://github.com/Insane96/EnhancedAI/files/10343161/crash-2023-01-04_10.11.50-server.txt)

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Not sure

**Comment by Insane96** [comment]
Fixed in latest 1.18.2 and 1.19.3 releases
