### ISSUE TITLE
Llamas can no longer spit if animal attacking is enabled

### ISSUE THREAD

**Issue by kristibektashi** [Insane96/EnhancedAI#72]
**Describe the bug**
When the option "Enable Animal Attacking" is enabled llamas (and trader llamas) can no longer spit. Instead they use melee attacks. I believe they should do both, using melee when their target is nearby, otherwise spitting them

**Versions:**
 - Minecraft: 1.19.2
 - Forge: 43.2.1
 - Enhanced AI: 1.8.1
 - InsaneLib: 1.7.2

**Steps to reproduce**
1. Make sure "Enable Animal Attacking" is turned on
2. Punch a llama (or summon a wolf near it)
3. 

**Screenshots**

**Logs**
Use a paste site (pastebin, gist) to send the game logs (both logs and crash if applicable)

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes/No

**Comment by Insane96** [comment]
I will just add Llamas to the animal blacklist by default

**Comment by kristibektashi** [comment]
> I will just add Llamas to the animal blacklist by default

What about Trader Llamas? They are also affected

**Comment by Insane96** [comment]
I will add both
