### ISSUE TITLE
[Suggestion] Mobs should be able to use both melee and ranged attacks

### ISSUE THREAD

**Issue by kristibektashi** [Insane96/EnhancedAI#73]
For example, skeletons should use melee when the player is too close to them (and they don't have the ability to flee). Drowned could replicate the Bedrock Edition behavior, where they use melee when their target is less than 3 blocks away, otherwise using ranged attacks. There are probably more cases where this logic could be applied

**Comment by Insane96** [comment]
Not gonna change skeletons, I think every mob should have its role. If every mob can do everything, there's no longer uniqueness.
I like the idea of making drowned attack melee if 3 blocks away like BE
