### ISSUE TITLE
Mobs should be able to use more weapons

### ISSUE THREAD

**Issue by kristibektashi** [Insane96/EnhancedAI#74]
For example, zombies should be able to use bows (and maybe even crossbows) if they somehow pick them up or they could have a small chance to spawn with them. This could also apply to zombified piglins, which can hold crossbows in the overworld.

More ideas: Skeletons using crossbows, Pillagers using regular bows and melee, illusioners using crossbows and melee, evokers using melee when their target gets too close, vindicators using bows and crossbows should they pick them up, piglins using regular bows

**Comment by Insane96** [comment]
As already mentioned in the other issue
> I think every mob should have its role. If every mob can do everything, there's no longer uniqueness
