### ISSUE TITLE
Found Incompatibilities

### ISSUE THREAD

**Issue by Nagasena12** [Insane96/EnhancedAI#76]
Mobs getting insane speed and damage increase when using together with Project MMO

 - Minecraft : 1.18.2
 - Forge:  40.2.0
 - Enhanced AI: 1.6.5 for 1.18.2
 - InsaneLib: 1.5.3 for 1.18.2
 - Project MMO: 5.1.3 for 1.18.2

I tried to remove Project MMO and it worked properly. I tried to edit the server config of pmmo autovalues and server, setting mobs scaling and auto values to false but nothing changed. Currently I am trying to use AtrributeFix mod to fix the problem, meanwhile I report this incompatibity

**Comment by Insane96** [comment]
EnhancedAI doesn't change mobs speed, report to PMMO too

**Comment by Nagasena12** [comment]
Okay I'll report

**Comment by Nagasena12** [comment]
Tra l'altro grande lavoro bro, hai creato davvero una bella mod

**Comment by Nagasena12** [comment]
I solved the problem. It seems that enhanced AI and pmmo don't work together only if before disabling mobs scaling in the pmmo.server file you give yourself pmmo levels via commands. Now that I have disabled mobs scaling BEFORE giving me levels there are no more problems.
So to fix the problem just go to your server config folder and search pmmo.server, then set mobs scaling to false
