### ISSUE TITLE
[Suggestion] Additional AI Options for Mobs Forcefully Equipped With Gear

### ISSUE THREAD

**Issue by ZilverLazarus** [Insane96/EnhancedAI#78]
Recently, I've been working with JEMs (JSON Entity Models) and I came up with the idea of creepers holding gear or items in their mouths when they're given something by either a mod spawning them like that or /summon.
![Combat Creeper](https://user-images.githubusercontent.com/83998931/216679975-85ba290c-7708-4386-bd9f-287f4c3ea334.png)

JEMs allows anything to render armor/tools/weapons/etc, and when paired with a mod like Improved Mobs (which force-equips any mob with armor/gear regardless of whether or not it renders), you get some amazing and terrifying results.

This inspired me to come here and ask for an addition that I believe fits the scope of this mod: additional AI options for mobs that are forcefully equipped with gear. What do I mean by this? Let me answer that question with the actual suggestions/requests.

-Creepers that are equipped with melee weapons will move towards the player like usual, but instead of immediately trying to blow up, they will melee attack the player. They will only resort to blowing themselves up when at low health in this circumstance.

-Witches that are equipped with melee weapons will counterattack the player using that melee weapon if the player is running at them. Witches will still use potions at close range to weaken players and will sometimes combine this into their counterattack. If the player is fleeing from the witch, it will then resort to chasing and throwing potions at the player.

I would greatly appreciate it if this was added. Thank you for reading and hopefully you found this suggestion interesting. ^^

**Comment by Insane96** [comment]
I don't like making every mob have the same attack. I like them having different reason to exist.
