### ISSUE TITLE
EnhancedAI Creepers Crashing the Game with Immersive Engineering Revolver

### ISSUE THREAD

**Issue by Mathead253** [Insane96/EnhancedAI#79]
**Describe the bug**
Whenever I fire a Immersive Engineering revolver at any number of creepers in creative my game crashes 

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 - Enhanced AI: 1.2.3
 - InsaneLib: 1.4.2

**Steps to reproduce**
1. Open a creative world
2. Spawn in any number of creepers
3. Shoot them with any ammo in the immersive engineering revolver

**Logs**
Use a paste site (pastebin, gist) to send the game logs (both logs and crash if applicable)
Crash Report: https://pastebin.com/sp2HW7v1
Log: https://pastebin.com/85mc3QdL

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes (EnhancedAI + InsaneLib + Immersive Engineering)

**Comment by Insane96** [comment]
That's not possible as the target is checked earlier and the creeper cannot be null. IE might be doing something strange.

**Comment by Mathead253** [comment]
I think you're right because shooting the IE revolver at creepers (or mobs like skeletons or zombies) allows them to target a player in creative mode. I think this is what's causing the issue because no crashes occur in survival throughout my testing.

I don't think this is a major issue but I'm going to close this issue and create a new one on the IE issue tracker.
