### ISSUE TITLE
Suggestion: Zombies can dig bellow sea level, and drowned can dig

### ISSUE THREAD

**Issue by CTH999** [Insane96/EnhancedAI#89]
So, my suggestion is 2.5-fold:

1. Drowned can now mine blocks underwater, using their trident. It's slow, but they will use it as a breaching behaviour.
2. Zombies have ~2 modificitations
2a. They can dig underground (They will only dig to target players, and the chance to be able to dig below sea level is like 75%, but _only if_ they can dig to begin with! (They can't dig in water though. But, they can have the drowned do that...)
2b. They will _work with_ drowned. The drowned can dig them a tunnel to more easily reach the inside and stay land-breathing! Creepers will also work with them to breach that tunnel!

note: 2a is the easiest, 1 is the second easiest, 2b is a bit overcomplicated

**Comment by Insane96** [comment]
This seems way too overcomplicated

**Comment by CTH999** [comment]
yeah... the first part (below sea level) is probally easy. Same with the no digging in water.

The drowned mechanics are where it gets complex...

**Comment by Insane96** [comment]
Drowneds can already mine blocks underwater as they are Zombies.
Making them work together is something I don't want to do. Zombies are brainless, they don't work together
