### ISSUE TITLE
[Suggestion] Regarding Ladders

### ISSUE THREAD

**Issue by utterlynowhere** [Insane96/EnhancedAI#9]
Is it possible to implement pathfinding for hostile mobs to climb ladders and scaffoldings? Thank you!

**Comment by Insane96** [comment]
I don't really know if it's possible

**Comment by SandwichHorror** [comment]
If it's at all relevant, the mod Improved Mobs has a feature where mobs climb ladders (but not scaffolds)
https://www.curseforge.com/minecraft/mc-mods/improved-mobs

I haven't tested it enough to personally speak of how it works in game, and the mod is ARR but open source. 

Hopefully that helps you in some way.

**Comment by Insane96** [comment]
Implemented for next update.
