### ISSUE TITLE
Suggestion: Ability to controll probability of enchantment and other things based on stats

### ISSUE THREAD

**Issue by CTH999** [Insane96/EnhancedAI#90]
So, what would be nice, I think, is the ability to manipulate just how likley mobs are to have enchanted are to have different enchantments on their weapons, as well as the max and minimum teir, what influences that, ect. For instance, do they get stronger enchantments based on the moon? the age of the world? The distance from the day? A combination thereof? _you_ choose! Maybe skeletons are more likley to have punch than power, or do you want it the other way? Manipulate the chances of it. Maybe they are always guarenteed to have enchantments. Or not at all. Or based on a system similar to [Progressive Bosses](https://www.curseforge.com/minecraft/mc-mods/progressive-bosses)

**Comment by Insane96** [comment]
You can already do this and more with Mobs Properties Randomness

**Comment by CTH999** [comment]
fair enough.

**Comment by Insane96** [comment]
Like the idea of having the moon as a modifier

**Comment by CTH999** [comment]
> Like the idea of having the moon as a modifier

Glad you like it!
