### ISSUE TITLE
Suggestion: Melee Skeletons

### ISSUE THREAD

**Issue by CTH999** [Insane96/EnhancedAI#91]
So, a semi-little-known fact is that skeletons are capable of Melee. So, my idea is this: _if_ you get too close to a skeleton, it will (if it is the type that tries to escape, escape), if not, it will start attacking you. 

It also has a chance to spawn with a Sword to attack. Sometimes the sword is an as-well (it will switch to the sword if you are closer), other times the sword is an _only_, in which case they will act more like a Zombie, _but_ will be a bit more cautious

This will work _really_ well with the whole "using shields" (if they spawn with one)

**Comment by Insane96** [comment]
I don't really like the idea of having Skeletons melee. I prefer to keep them ranged.

I might implement this anyway in the future

**Comment by CTH999** [comment]
makes sense!

**Comment by Insane96** [comment]
Duplicated of #80
