### ISSUE TITLE
Suggestion: Wither Skeleton improvments

### ISSUE THREAD

**Issue by CTH999** [Insane96/EnhancedAI#92]
So, a wither skeletons can fire bows, and when they do it _always_ acts as if they have Flame on it. However, what if there was the following:

1. A chance for wither skeletons to have a bow instead (and act like a regular skeleton mostly, albiet trying to be a little closer)
2. The bow (configurably) causes the wither effect as well as fire (choose between only fire, only wither, both, or chance). If chance, you can randomize it! Maybe it typically causes wither, sometimes causes both!
3. A chance for them to have both. They will _try_ to do melee, but if they can't... then they will use their bow (or it could be a chance for each preference. 50% of neutral, 25% to try to use bow mostly, 25% to prefer melee? (As defaults))
4. A chance for them to be able to summon normal skeletons (possibly "pulling" them out of the soul sand) to help defend them. Maybe these skeletons are unarmed? Or maybe not... maybe most of the time un-armed, but not always? Maybe they are faster?
5. A chance for them to have better weapons! Typically it is just their normal stone sword, but... they might also have better ones!
6. They are more likley to have better enchants than typical skeletons

**Comment by Insane96** [comment]
Yeah, like the idea of improving them.

1. Wither skeletons should already act like a skeleton if wielding a bow, so that shouldn't be a problem
2. - [x] Having both active makes no sense, as the invincibility frames will block one of them
3. As the previous suggesion, I don't like this
4. This is definitely too much for a normal mob
5. The wither effect is already strong enough
6. Use MobsPropertiesRandomness

**Comment by CTH999** [comment]
Great!
Note: Reading through this, realized some of it could be taken as arguing/ complaining. So, I just want you to know that it isn't, it's just pure curiosity. I have never been the best with (rapid) wording (writing something quickly), nor asking lots of questions and coming off calmly. So, if you interpret this as arguing, I am sorry. I swear, it is not meant to be that way.

1. Yeah, by far the easiest :)
2. true. It could be that _rarely_ the skeletons can do both, randomly per arrow? But, that is way over-complex. I mean, the capability to do that, and someone can access it via MobsPropertiesRandomness is neat, but way overcomplex
3. Okay. Just out of curiosity (To factor into any future suggestions), why? Is it because that would require weighting different attack styles but allowing both?
4. Okay. I was just thinking along the lines of the Dark Arts (that witches' can do). And, Wither Skeletons aren't exactly normal mobs... but, makes sense!
5. yeah, and a cruel modpack author could use that MobsPropertiesRandomness mod to randomize weapons (if I understand it right). No modpack author would be _that_ cruel... *Looks at the modpack he's making, with these features*
6. Yeah, when I wrote this I wasn't sure of that mods full power. Even with experiments, still aren't sure (But definitely _terrified_!

**Comment by Insane96** [comment]
I don't see that as complaining, I like having a convo about ideas.

> true. It could be that rarely the skeletons can do both, randomly per arrow? But, that is way over-complex. I mean, the capability to do that, and someone can access it via MobsPropertiesRandomness is neat, but way overcomplex

I preffer them to be more in line with the fact they are wither skeletons and shoot wither arrows instead of fire arrow. I don't really know why mojang made them shoot fire arrows.

> Okay. Just out of curiosity (To factor into any future suggestions), why? Is it because that would require weighting different attack styles but allowing both?

I preffer mobs to have one job only. Many people ask me "can you make skeletons able to mine?" And I always scrap the idea, as I like each mob having a role. I'm still not sure if I want this melee/ranged thing for skeletons. We'll see

> Okay. I was just thinking along the lines of the Dark Arts (that witches' can do). And, Wither Skeletons aren't exactly normal mobs... but, makes sense!

True but witches are rarer, that's why I liked them to have a "special" move

> yeah, and a cruel modpack author could use that MobsPropertiesRandomness mod to randomize weapons (if I understand it right). No modpack author would be that cruel... Looks at the modpack he's making, with these features

> Yeah, when I wrote this I wasn't sure of that mods full power. Even with experiments, still aren't sure (But definitely terrified!

Yeah, MPR is the solution for more complex stuff. I'm ok making them spawn with a bow, but that's it, any further changes should be made with MPR. That's even the reason I made MPR lol

**Comment by CTH999** [comment]
> I don't see that as complaining, I like having a convo about ideas.

great! A like mind!

> I prefer them to be more in line with the fact they are wither skeletons and shoot wither arrows instead of fire arrow. I don't really know why Mojang made them shoot fire arrows.

kind of the idea I prefer.

> Mojang made them shoot fire arrows.
2 reasons. 
1. They are Mojang
2. Nether. Nether=fire


> I prefer mobs to have one job only. Many people ask me "can you make skeletons able to mine?" And I always scrap the idea, as I like each mob having a role. I'm still not sure if I want this melee/ranged thing for skeletons. We'll see

that makes a lot of sense! I like! Mining skeletons doesn't make a whole lot of sense imo. 
Also, I'm assuming MPR can do that?


> True but witches are rarer, that's why I liked them to have a "special" move 

Good point! Also, Makes me think the Evoker deserves some work. Or the Illusioner! I'll probably be back with ideas on those two...)


> Yeah, MPR is the solution for more complex stuff. I'm ok making them spawn with a bow, but that's it, any further changes should be made with MPR. That's even the reason I made MPR lol

I figured that's why (:

**Comment by Insane96** [comment]
* No, you can't make skeletons mine with MPR, the digger ai is only added to zombies like mobs.
* Yeah, the evoker might have something new. I'm not gonna tamper with the Illusioner, it's an unfinished mob.

**Comment by CTH999** [comment]
Makes sense on the first one.

Can't wait for the evoker one! But, the illusioner, well, you could finish it, as most of what wasn't finished (if I understand correctly), is the AI, which this mod is changing anyways!

**Comment by Insane96** [comment]
Nah, I'm not gonna touch an unfinished mob that might chance/disappear (pun intended) at any time.

Also implemented the Wither Skeletons Changes!
