### ISSUE TITLE
[1.19.2] Editing the config to disable xray and follow range modifications doesn't work

### ISSUE THREAD

**Issue by BugmanBugman** [Insane96/EnhancedAI#94]
**Describe the bug**  
Editing the config to make the xray and follow range options disabled does not work. The mobs still target you no matter what. I change both min and max values of both options to 0,  yet all hostile mobs could target me from long ranges

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.2.11
 - Enhanced AI: 1.8.1
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   Set xray and follow range values to 0 in config
2.   spawn in any hostile mob
3.   notice how they still target you farther away than in vanilla

**Screenshots**  

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

**Comment by Insane96** [comment]
This is a known bug. Thanks for reporting it. In the meantime just set the xray values to 1 to prevent the infinite range targeting

**Comment by Insane96** [comment]
This has been fixed in 1.19.4 and up
