### ISSUE TITLE
ticking witch?

### ISSUE THREAD

**Issue by kaairu** [Insane96/EnhancedAI#95]
**Describe the bug**  
a witch is causing my game to crash I think

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft:  1.19.2
 - Forge: 43.2.11
 - Enhanced AI: EnhancedAI-1.8.1-mc1.19.2.
 - InsaneLib: 
InsaneLib-1.7.5-mc1.19.2

**Steps to reproduce**  
idk I joined my game a witch or something is js messing w enhanced ai, I think

**Screenshots**  
n/a

**Logs**  
https://paste.modularity.gg/paste/?content=https://cdn.discordapp.com/attachments/1101396706861531157/1110065934258937856/latest.log&raw=false

https://paste.modularity.gg/paste/?content=https://cdn.discordapp.com/attachments/1101396706861531157/1110065934548357160/crash-2023-05-21_21.43.03-server.txt&raw=false

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
No?

**Comment by Insane96** [comment]
BigBrain is messing with witches

**Comment by seymourimadeit** [comment]
Looking from the crash log I personally feel like it's actually just a problem with the DarkArtWitchGoal not checking if the look target should be null or not. I will find any problems with my code though. 

https://github.com/Insane96/EnhancedAI/blob/1.19.x/src/main/java/insane96mcp/enhancedai/modules/witch/ai/DarkArtWitchGoal.java#LL98C82-L98C82

**Comment by Insane96** [comment]
Yeah, but the target shouldn't be null at that point
