### ISSUE TITLE
Enhanced AI cannot has issues related to the config file.

### ISSUE THREAD

**Issue by Zebrahawk** [Insane96/EnhancedAI#98]
**Describe the bug**  
Basically upon booting a server running Minecraft Forge 1.19.2 using the Cursed Walking modpack by OnMod, I added Enhanced AI to make the server a bit more engaging and after the nightly restart it wouldn't reboot. I had to do extensive research to conclude that Enhanced AI was causing it. It has something to do with the configuration file because once I deleted the configuration file it booted normally. If my file is incorrectly formatted that may also be it but I feel that I am not doing anything wrong. I will also give the console log.
**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.19.2
 - Forge: 43.2.0
 - Enhanced AI: 1.8.0
 - InsaneLib: 1.7.5

**Steps to reproduce**  
1.   Launch game?

**Logs**  
https://pastebin.com/SU1gLYz2
(A zip of the mods used below)
https://cdn.discordapp.com/attachments/1026240780492345375/1132396982388928632/mdZP5ck.zip
**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Likely not. I am still experimenting with mod compatibility.

**Comment by Insane96** [comment]
I randomly get this problem too, I think it's just a problem with the config library. I can't do much about it.
